---
- name: Runs for 5 minutes
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 11
        delay: 30
  rules:
    - name: rule with 1 action
      condition: event.i > 0
      actions:
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true

