- name: test kafka source plugin with plaintext security protocol and listening to pattern matched topics
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        topic_pattern: "{{ kafka_topic_pattern | default('kafka-events') }}"
        metadata_max_age_ms: "{{ meta_interval | default('300000') }}"
        host: "{{ kafka_host | default('host.containers.internal') }}"
        port: "{{ kafka_port | default(9093) }}"
        offset: "{{ offset | default('latest') }}"
        group_id: "{{ group_id }}"
        encoding: ascii
  rules:
    - name: match kafka event
      condition: event.body.name == "eda"
      action:
        debug:
          msg: "Rule fired successfully for PLAINTEXT consumers"

    - name: stop
      condition: event.body == "stop"
      action:
        shutdown:

