- name: test kafka source plugin with plaintext security protocol
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        topics: "{{ kafka_topics | default(['kafka-events-1', 'kafka-events-2']) }}"
        host: localhost
        port: 9092
        offset: earliest
        encoding: ascii
  rules:
    - name: match kafka event
      condition: event.body.name == "Produced for PLAINTEXT consumers"
      action:
        debug:
          msg: "Rule fired successfully for PLAINTEXT consumers"

    - name: stop
      condition: event.body == "stop"
      action:
        shutdown:

    - name: match kafka event22
      condition: event.body.name == "Produced for PLAINTEXT consumers 2"
      action:
        debug:
          msg: "Rule fired successfully for PLAINTEXT consumers 2"