---
- name: Test rules simple
  hosts: all
  sources:
    - name: ansible.eda.range
      ansible.eda.range:
        limit: 5
  rules:
    - name: r1
      condition: event.i == 0
      action:
        print_event:
          pretty: true
          var_root: i
    - name: r2
      condition: event.i == 1
      action:
        print_event:
    - name: r4
      condition: event.msg is defined
      action:
        print_event:


