---
- name: Test servicenow connection
  hosts: all
  sources:
    - name: servicenow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 6666
        token: tiktok
  rules:
    - name: rule1
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
          
