---
- name: Test servicenow connection
  hosts: all
  sources:
    - name: servicenow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 6666
        service: snow-webhook
        token: '{{ webhook_token }}'
  rules:
    - name: rule1
      condition: event.payload.changes[0].ref.displayId == 'dev'
      action:
        print_event:
          pretty: true
          
