---
- name: Test servicenow connection
  hosts: all
  sources:
    - name: servicenow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5555
        token: '{{ webhook_token }}'
        certfile: '{{ certfile }}'
        keyfile: '{{ keyfile }}'
  rules:
    - name: rule1
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
          
