---
- name: Test webhook tls
  hosts: all
  sources:
    - name: webhook with tls
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5555
  rules:
    - name: rule1
      condition: event.payload.name == vars.USER_NAME
      action:
        debug:
          msg: "User {{ USER_NAME }} is here"
    - name: Shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
          
