---
- name: Simple webhook
  hosts: all
  sources:
    - name: webhook with tls
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5555
  rules:
    - name: rule1
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
          
